---

- set_fact:
    logger:           "splunk"
    log_opts:
      splunk-token: '{{ hostvars[groups["indexers"][0]].splunk_hec_tokens.logging_tok.value }}'
      splunk-index: '{{ hostvars[groups["indexers"][0]].splunk_hec_tokens.logging_tok.index }}'
      splunk-url:   '{{ "https" if splunk_secured else "http" }}://{{ hostvars[groups["indexers"][0]].public_host_name }}.{{ common_name }}:{{ splunk_hec_port }}'