# IMPORTANT!  If using Splunk, you need at _least_ 1GB of ram
# Vagrant has only 500MB out of the box

---
# tasks file for splunk-docker

- name: Create data container
  docker_container:
    name: '{{ splunk_container_name + "-data" }}'
    image: busybox
    state: present
    volumes:
      - /opt/splunk/var/lib/splunk
  when: splunk_use_data_container

- name: Pull Splunk image
  docker_image:
    name: '{{ splunk_docker_image }}'
    tag:  '{{ splunk_docker_image_tag }}'

- name: Setup Splunk container
  docker_container:
    name:  '{{ splunk_container_name }}'
    image: '{{ splunk_docker_image }}:{{ splunk_docker_image_tag }}'
    state:  started
    ports:
      - '{{ splunk_http_port }}:8000'
      - '{{ splunk_admin_port }}:8088'
      - '{{ splunk_hec_port }}:8089'
    volumes_from: ['{{ ( splunk_container_name + "-data" ) if splunk_use_data_container else None | default(omit) }}']
    volumes: ['{{ (splunk_data_dir + ":/opt/splunk/var/lib/splunk") if not splunk_use_data_container else None | default(omit) }}']
    env:
      TZ: '{{ splunk_container_timezone }}'
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_USER:  "splunk"
      SPLUNK_CMD:   "edit user admin -password {{ splunk_password }} -role admin -auth admin:changeme"
  register: splunk_container

- name: Wait until Splunk is available
  wait_for: port={{ splunk_http_port }} delay=3
  when: splunk_container.changed
